source: _source
destination: _build

server: true

permalink: /produtos/:categories/:title/
paginate_path: "produtos/pagina:num"
paginate: 5

host:        localhost
port:        4000
baseurl:     / 
url:         http://localhost:4000