source: _source
destination: _build

permalink: /produtos/:categories/:title/
paginate_path: "produtos/pagina:num"
paginate: 5

host:        http://localhost
port:        4000
baseurl:     /
url:         http://localhost:4000